export enum ClientsTable {
   clientId = 'clientId',
   clientName = 'clientName',
   contactName = 'contactName',
   emailAddress = 'emailAddress',
   phone1CountryCode = 'phone1CountryCode',
   phone1Number = 'phone1Number',
   phone1Ext = 'phone1Ext',
   phone2CountryCode = 'phone2CountryCode',
   phone2Number = 'phone2Number',
   phone2Ext = 'phone2Ext',
   website = 'website',
   addressLine1 = 'addressLine1',
   addressLine2 = 'addressLine2',
   city = 'city',
   state = 'state',
   country = 'country',
   zip = 'zip',
   createDate = 'createDate',
   createUserId = 'createUserId',
   updateDate = 'updateDate',
   updateUserId = 'updateUserId'
 }