export enum ProjectsTable {
  projectId = 'projectId',
  projectName = 'projectName',
  complexity = 'complexity',
  poNumber = 'poNumber',
  assignedTo = 'assignedTo',
  poDate = 'poDate',
  clientHours = 'clientHours',
  receivedDate = 'receivedDate',
  conFolderLink = 'conFolderLink',
  targetedOfaDate = 'targetedOfaDate',
  actualOfaDate = 'actualOfaDate',
  bfaDate = 'bfaDate',
  fabricationDate = 'fabricationDate',
  remarks = 'remarks',
  status = 'status',
  createDate = 'createDate',
  createUserId = 'createUserId',
  updateDate = 'updateDate',
  updateUserId = 'updateUserId'
}
