export enum CODE {
  SKIP_NOTIF = 'Skip Notfication',
  INVALID_API_REQUEST = 'Invaliad API',
  NO_SESSION_ID_FOUND = 'Missing Session',
  INVALID_SESSION = 'Invalid Session',
  INVALID_DML_DATA = 'Invliad DML Data',
  INVALID_DML_OPERATION = 'Invalid DML Operation',
  INVALID_API_OPERATION = 'Invalid API Operation',
  QUERY_NOT_ALLOWED = 'Query not Allowed',
  NO_PK_DEF = 'Missing configuration',
  NO_PK_DATA = 'Missing configuration',
  NO_AUDIT_COLUMNS = 'Missing configuration',
  ERR_WHILE_QUERY = 'Error while query',
  ERR_BEFORE_QUERY = 'Error before query',
  ERR_AFTER_QUERY = 'Error after query',
  ERR_BERORE_DML = 'Error before DML',
  ERR_AFTER_DML = 'Error After DML',
  ERR_WHILE_DML = 'Error while save',
  INVALID_USER_PASS = 'Login Error',
  SYSTEM_ERR = 'System Error',
  NO_USER = 'Login Error',
  INVALID_PASSWORD = 'Incorrect password, please verify!',
  ERR_WHILE_POST = 'Error while posting',
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR'
}
